import { PartyRecord } from "./types";

export const DUMMY_CUSTOMERS: PartyRecord[] = [
  {
    id: 1,
    party_id: 1,
    party_name: "Apex Global Solutions Pvt Ltd",
    contact_name: "Rajesh Sharma",
    email: "rajesh.sharma@apexglobal.in",
    phone: "+91 98200 12345",
    gst_no: "27AAACA123411Z5",
    pan_no: "AAACA12341",
    opening_balance: 154500.00,
    status: "active",
    website: "www.apexglobal.in",
    notes: "Key enterprise client for automotive components.",
    addresses: [
      {
        address_id: 101,
        address_label: "Headquarters & Billing",
        address_type: "billing",
        address_line1: "Plot 42, MIDC Industrial Area, Phase II",
        address_line2: "Andheri East",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400093",
        attention_to: "Accounts Payable Dept",
      },
      {
        address_id: 102,
        address_label: "Bhiwandi Warehouse",
        address_type: "shipping",
        address_line1: "Shed No. 12, Indian Logistics Park",
        address_line2: "Val Village, Bhiwandi",
        city: "Thane",
        state: "Maharashtra",
        pincode: "421302",
        attention_to: "Warehouse Manager - Mr. Anil",
      },
    ],
    contactPersons: [
      {
        person_id: 201,
        name: "Rajesh Sharma",
        email: "rajesh.sharma@apexglobal.in",
        phone: "+91 98200 12345",
        designation: "VP Procurement",
      },
      {
        person_id: 202,
        name: "Priya Nair",
        email: "priya.nair@apexglobal.in",
        phone: "+91 98200 54321",
        designation: "Senior Accounts Officer",
      },
    ],
  },
  {
    id: 2,
    party_id: 2,
    party_name: "Reliance Industrial Infra Tech",
    contact_name: "Sanjay Verma",
    email: "procurement@riitech.com",
    phone: "+91 98111 67890",
    gst_no: "07AABCR5678E1Z9",
    pan_no: "AABCR5678E",
    opening_balance: 489000.50,
    status: "active",
    website: "www.riitech.com",
    notes: "Standard 30-day payment term under corporate agreement.",
    addresses: [
      {
        address_id: 103,
        address_label: "Corporate Office",
        address_type: "billing",
        address_line1: "8th Floor, Cyber Towers, DLF Phase 3",
        city: "Gurugram",
        state: "Haryana",
        pincode: "122002",
        attention_to: "Finance Team",
      },
    ],
    contactPersons: [
      {
        person_id: 203,
        name: "Sanjay Verma",
        email: "sanjay.v@riitech.com",
        phone: "+91 98111 67890",
        designation: "General Manager - Supply Chain",
      },
    ],
  },
  {
    id: 3,
    party_id: 3,
    party_name: "Vanguard Engineering & Automation",
    contact_name: "Amitabh Sen",
    email: "orders@vanguardauto.co.in",
    phone: "+91 94330 99887",
    gst_no: "19AADCV9876K1Z3",
    pan_no: "AADCV9876K",
    opening_balance: 0.00,
    status: "active",
    website: "www.vanguardauto.co.in",
    notes: "Requires e-way bill copy attached with all consignments.",
    addresses: [
      {
        address_id: 104,
        address_label: "Kolkata Plant",
        address_type: "both",
        address_line1: "Sector V, Salt Lake City",
        city: "Kolkata",
        state: "West Bengal",
        pincode: "700091",
        attention_to: "Dispatch Counter",
      },
    ],
    contactPersons: [
      {
        person_id: 204,
        name: "Amitabh Sen",
        email: "amitabh.sen@vanguardauto.co.in",
        phone: "+91 94330 99887",
        designation: "Plant Manager",
      },
    ],
  },
  {
    id: 4,
    party_id: 4,
    party_name: "Zeta Logistics Services India",
    contact_name: "Vikram Malhotra",
    email: "billing@zetalogistics.in",
    phone: "+91 97444 33221",
    gst_no: "29AABCZ4321J1Z8",
    pan_no: "AABCZ4321J",
    opening_balance: 62400.00,
    status: "active",
    website: "www.zetalogistics.in",
    notes: "Prefers monthly consolidated invoicing.",
    addresses: [
      {
        address_id: 105,
        address_label: "Bangalore Logistics Hub",
        address_type: "billing",
        address_line1: "Electronic City Phase 1",
        city: "Bengaluru",
        state: "Karnataka",
        pincode: "560100",
        attention_to: "Billing Operations",
      },
    ],
    contactPersons: [],
  },
];

export const DUMMY_VENDORS: PartyRecord[] = [
  {
    id: 5,
    party_id: 5,
    party_name: "Steel Kraft Industries India",
    contact_name: "Harish Patel",
    email: "sales@steelkraft.co.in",
    phone: "+91 98250 88776",
    gst_no: "24AABCS9988P1Z1",
    pan_no: "AABCS9988P",
    opening_balance: 245000.00,
    status: "active",
    website: "www.steelkraft.co.in",
    notes: "Primary raw steel and alloy sheet supplier.",
    addresses: [
      {
        address_id: 106,
        address_label: "GIDC Manufacturing Works",
        address_type: "both",
        address_line1: "GIDC Industrial Estate, Vatva",
        city: "Ahmedabad",
        state: "Gujarat",
        pincode: "382445",
        attention_to: "Dispatch & Billing Dept",
      },
    ],
    contactPersons: [
      {
        person_id: 205,
        name: "Harish Patel",
        email: "h.patel@steelkraft.co.in",
        phone: "+91 98250 88776",
        designation: "Commercial Manager",
      },
    ],
  },
  {
    id: 6,
    party_id: 6,
    party_name: "Polymer Tech Packaging Ltd",
    contact_name: "Kavita Deshmukh",
    email: "info@polymertech.in",
    phone: "+91 98900 55443",
    gst_no: "27AABCP1122D1Z7",
    pan_no: "AABCP1122D",
    opening_balance: 78200.00,
    status: "active",
    website: "www.polymertech.in",
    notes: "Corrugated box and protective bubblewrap packaging vendor.",
    addresses: [
      {
        address_id: 107,
        address_label: "Chakan Plant",
        address_type: "billing",
        address_line1: "Chakan Industrial Area, Phase 3",
        city: "Pune",
        state: "Maharashtra",
        pincode: "410501",
        attention_to: "Accounts Section",
      },
    ],
    contactPersons: [
      {
        person_id: 206,
        name: "Kavita Deshmukh",
        email: "kavita@polymertech.in",
        phone: "+91 98900 55443",
        designation: "Key Account Executive",
      },
    ],
  },
  {
    id: 7,
    party_id: 7,
    party_name: "Precision Tools & Fasteners Co",
    contact_name: "Sunil Kumar",
    email: "orders@precisiontools.com",
    phone: "+91 98100 44332",
    gst_no: "06AABCP7766M1Z2",
    pan_no: "AABCP7766M",
    opening_balance: 18500.00,
    status: "active",
    website: "www.precisiontools.com",
    notes: "Hardware, bolts, and specialized cutting tool supplier.",
    addresses: [
      {
        address_id: 108,
        address_label: "Faridabad Unit",
        address_type: "both",
        address_line1: "Mathura Road Industrial Area",
        city: "Faridabad",
        state: "Haryana",
        pincode: "121003",
        attention_to: "Sales Operations",
      },
    ],
    contactPersons: [],
  },
];
